openapi: 3.0.0
info:
  title: Train Tracking System API
  description: API documentation for the Train Tracking System
  version: 1.0.0

servers:
  - url: http://localhost:8020/api
    description: Local server

paths:
  /trains/add:
    post:
      summary: Add a new train
      tags:
        - Trains
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                engineId:
                  type: string
                  example: T001
                route:
                  type: string
                  example: Colombo to Badulla
      responses:
        200:
          description: Train has been added
        500:
          description: Server error

  /trains/get:
    get:
      summary: Get all trains
      tags:
        - Trains
      responses:
        200:
          description: A list of trains
        500:
          description: Server error

  /trains/get/{id}:
    get:
      summary: Get a train by ID
      tags:
        - Trains
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The train ID
      responses:
        200:
          description: Train details
        500:
          description: Server error
